/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarTuningConfig {
  'tuningParams' : TuningParameters,
  'driveMode' : DriveMode,
}
export type DriveMode = { 'city' : null } |
  { 'classic' : null } |
  { 'sports' : null };
export interface FuelInjectionSettings {
  'temperature' : number,
  'pressure' : number,
  'amount' : number,
}
export interface ScooterTuning {
  'weight' : number,
  'maxSpeed' : number,
  'acceleration' : number,
  'handling' : number,
}
export interface TuningParameters {
  'suspensionStiffness' : number,
  'brakeBias' : number,
  'steeringSensitivity' : number,
  'throttleResponse' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFuelInjectionSettings' : ActorMethod<[], [] | [FuelInjectionSettings]>,
  'getScooterTuningConfig' : ActorMethod<[], [] | [ScooterTuning]>,
  'getThrottleSetting' : ActorMethod<[], bigint>,
  'getTuningConfig' : ActorMethod<[], [] | [CarTuningConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFuelInjectionSettings' : ActorMethod<[FuelInjectionSettings], undefined>,
  'saveScooterTuningConfig' : ActorMethod<[ScooterTuning], undefined>,
  'saveThrottleSetting' : ActorMethod<[bigint], undefined>,
  'saveTuningConfig' : ActorMethod<[CarTuningConfig], undefined>,
  'updateDriveMode' : ActorMethod<[DriveMode], undefined>,
  'updateTuningParameters' : ActorMethod<[TuningParameters], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];