/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FuelInjectionSettings = IDL.Record({
  'temperature' : IDL.Float64,
  'pressure' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const ScooterTuning = IDL.Record({
  'weight' : IDL.Float64,
  'maxSpeed' : IDL.Float64,
  'acceleration' : IDL.Float64,
  'handling' : IDL.Float64,
});
export const TuningParameters = IDL.Record({
  'suspensionStiffness' : IDL.Float64,
  'brakeBias' : IDL.Float64,
  'steeringSensitivity' : IDL.Float64,
  'throttleResponse' : IDL.Float64,
});
export const DriveMode = IDL.Variant({
  'city' : IDL.Null,
  'classic' : IDL.Null,
  'sports' : IDL.Null,
});
export const CarTuningConfig = IDL.Record({
  'tuningParams' : TuningParameters,
  'driveMode' : DriveMode,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFuelInjectionSettings' : IDL.Func(
      [],
      [IDL.Opt(FuelInjectionSettings)],
      ['query'],
    ),
  'getScooterTuningConfig' : IDL.Func([], [IDL.Opt(ScooterTuning)], ['query']),
  'getThrottleSetting' : IDL.Func([], [IDL.Nat], ['query']),
  'getTuningConfig' : IDL.Func([], [IDL.Opt(CarTuningConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFuelInjectionSettings' : IDL.Func([FuelInjectionSettings], [], []),
  'saveScooterTuningConfig' : IDL.Func([ScooterTuning], [], []),
  'saveThrottleSetting' : IDL.Func([IDL.Nat], [], []),
  'saveTuningConfig' : IDL.Func([CarTuningConfig], [], []),
  'updateDriveMode' : IDL.Func([DriveMode], [], []),
  'updateTuningParameters' : IDL.Func([TuningParameters], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FuelInjectionSettings = IDL.Record({
    'temperature' : IDL.Float64,
    'pressure' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const ScooterTuning = IDL.Record({
    'weight' : IDL.Float64,
    'maxSpeed' : IDL.Float64,
    'acceleration' : IDL.Float64,
    'handling' : IDL.Float64,
  });
  const TuningParameters = IDL.Record({
    'suspensionStiffness' : IDL.Float64,
    'brakeBias' : IDL.Float64,
    'steeringSensitivity' : IDL.Float64,
    'throttleResponse' : IDL.Float64,
  });
  const DriveMode = IDL.Variant({
    'city' : IDL.Null,
    'classic' : IDL.Null,
    'sports' : IDL.Null,
  });
  const CarTuningConfig = IDL.Record({
    'tuningParams' : TuningParameters,
    'driveMode' : DriveMode,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFuelInjectionSettings' : IDL.Func(
        [],
        [IDL.Opt(FuelInjectionSettings)],
        ['query'],
      ),
    'getScooterTuningConfig' : IDL.Func(
        [],
        [IDL.Opt(ScooterTuning)],
        ['query'],
      ),
    'getThrottleSetting' : IDL.Func([], [IDL.Nat], ['query']),
    'getTuningConfig' : IDL.Func([], [IDL.Opt(CarTuningConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFuelInjectionSettings' : IDL.Func([FuelInjectionSettings], [], []),
    'saveScooterTuningConfig' : IDL.Func([ScooterTuning], [], []),
    'saveThrottleSetting' : IDL.Func([IDL.Nat], [], []),
    'saveTuningConfig' : IDL.Func([CarTuningConfig], [], []),
    'updateDriveMode' : IDL.Func([DriveMode], [], []),
    'updateTuningParameters' : IDL.Func([TuningParameters], [], []),
  });
};

export const init = ({ IDL }) => { return []; };